In [22]:
import numpy as np
import time

In [16]:
def my_array(container):
    sum = 0
    for items in container:
        sum = sum + items
    
    avg = sum/len(container)
    
    temp = container[0]
    for first in container:
        if temp < first:
            temp = first
    max_value = temp
    
    temp = container[0]
    for first in container:
        if temp > first:
            temp = first
    min_value = temp
    
    my_output = {
        "min" : min_value,
        "max" : max_value,
        'avg' : avg
    }

    return my_output

In [18]:
my_array([12,22,33,43,52])

{'min': 12, 'max': 52, 'avg': 32.4}

In [19]:
%timeit my_array([12,22,33,43,52])

910 ns ± 87.4 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [20]:
x = np.array([[12,22,33,43,52]])

In [21]:
%timeit x

16.6 ns ± 0.504 ns per loop (mean ± std. dev. of 7 runs, 100000000 loops each)


In [23]:
t1 = time.time()

In [25]:
x = np.ones((3,3))

In [26]:
x

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [27]:
y = np.array([1,2,3])

In [28]:
x+y

array([[2., 3., 4.],
       [2., 3., 4.],
       [2., 3., 4.]])

# array broadcasting

In [29]:
yy = y.reshape((-1,1))

In [30]:
yy

array([[1],
       [2],
       [3]])

In [31]:
x+yy

array([[2., 2., 2.],
       [3., 3., 3.],
       [4., 4., 4.]])

In [32]:
z = 1

In [33]:
z+x

array([[2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.]])

In [34]:
z = np.array([1])

In [35]:
x+z

array([[2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.]])