In [1]:
print("31st Jan")

31st Jan


In [7]:
import numpy as np

import pyautogui
import time
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.support.ui import Select
import time
import cv2
import bs4
from tkinter import *
from tkinter import messagebox
executable_path = "C:\\Users\\Katlic\\Downloads\\web_drivers_chrome\\chromedriver.exe"


In [8]:
x = 0
while x < 4:
    pyautogui.screenshot("C:\\Users\\Katlic\\Pictures\\auto_screen_shots\\images" + str(x) + ".png")
    x += 1
    time.sleep(2)

In [15]:
 a = np.array([1,2,3,4], dtype='int16')
print(a)

[1 2 3 4]


In [5]:
b = np.array([[1,2,3,4],[5,6,7,8]])

In [9]:
for items in b:
    for item in items:
        print(item, end=" ")
    print()

1 2 3 4 
5 6 7 8 


In [10]:
b.ndim

2

In [11]:
a.ndim

1

In [12]:
b.shape

(2, 4)

In [13]:
a.shape

(4,)

In [16]:
b.dtype

dtype('int32')

In [17]:
a.dtype

dtype('int16')

In [18]:
a.itemsize

2

In [19]:
b.itemsize

4

In [20]:
b.nbytes

32

In [5]:


url = "https://courses.learncodeonline.in/learn"

driver = webdriver.Chrome(executable_path=executable_path)
driver.get(url)

courses = driver.find_elements_by_id('courseAvailList')

file = open("loc_courses.txt", "a+", encoding="utf-8")
for items in courses:
    file.write(items.text)
    file.write("\n\n")
file.close()
driver.quit()

In [10]:
url = "https://www.youtube.com/playlist?list=WL"
driver = webdriver.Chrome(executable_path=executable_path)
driver.get(url)

sign_in_button = driver.find_element_by_css_selector('class.yt-simple-endpoint style-scope ytd-button-renderer')
sign_in_button.click()


NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"class.yt-simple-endpoint style-scope ytd-button-renderer"}
  (Session info: chrome=79.0.3945.130)


In [2]:
container = np.array([1,2,3,4,5])

In [3]:
container

array([1, 2, 3, 4, 5])

In [4]:
import cv2
import numpy as np

cap = cv2.VideoCapture(0)

while 1:
    ret, frame = cap.read()
    gray = cv2.cvtColor (frame, cv2.COLOR_BGR2GRAY)
    
    
    cv2.imshow('frame', frame)
    cv2.imshow('gray', gray)
    
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break
        
cap.release()
cv2.destroyAllWindows()

In [1]:
import cv2
import numpy as np

cap = cv2.VideoCapture(0)
fourcc = cv2.VideoWriter_fourcc(*'XVID')
out = cv2.VideoWriter('output.avi',fourcc, 20.0, (640,480))

while 1:
    ret, frame = cap.read()
    gray = cv2.cvtColor (frame, cv2.COLOR_BGR2GRAY)
    
    
    cv2.imshow('frame', frame)
    cv2.imshow('gray', gray)
    
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break
        
cap.release()
out.release()
cv2.destroyAllWindows()

In [1]:


cap = cv2.VideoCapture(1)

while 1:
    
    _, frame = cap.read()
    hsv = cv2.cvtColor(frame, cv2.COLOR_BGR2HSV)
    
    lower_red = np.array([0,0,0])
    upper_red = np.array([255,255,255])
    
    mask = cv2.inRange(hsv, lower_red, upper_red)
    res = cv2.bitwise_and(frame, frame, mask = mask)
    
    cv2.imshow('frame', frame)
    cv2.imshow('mask', mask)
    cv2.imshow('res', res)
    
    k = cv2.waitKey(5) & 0xFF
    if k == 27:
        break
        
cv2.destroyAllWindows()
cap.release()

error: OpenCV(4.1.2) C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cv::cvtColor'


In [11]:
root = Tk()
root.geometry("300x400+40+40")
root.iconbitmap("C:\\Users\\Katlic\\Pictures\\a.BMP")
def popup():
    messagebox.showinfo("This is me", "Hello World")

Button(root, text = "Click for pop up", command=popup).pack()


root.mainloop()

In [12]:
a = np.array([[1,2,3,4,5,6], [7,8,9,10,11,12]])

In [13]:
a

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [14]:
a.shape

(2, 6)

In [15]:
a[1,4]

11

In [16]:
a[1,-2]

11

In [17]:
a[0,-2]

5

In [26]:
a[1,1:4]

array([ 8,  9, 10])

In [27]:
np.full((3,3), 90)

array([[90, 90, 90],
       [90, 90, 90],
       [90, 90, 90]])