In [2]:
import numpy as np

In [3]:
x = np.array([[1,2,3,4,5],[6,7,8,9,10]], dtype="int64")

In [4]:
x

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]], dtype=int64)

In [5]:
x.shape

(2, 5)

In [7]:
x.ndim

2

In [8]:
for items in x :
    print(items)

[1 2 3 4 5]
[ 6  7  8  9 10]


In [9]:
x.itemsize

8

In [10]:
x.dtype

dtype('int64')

In [11]:
x.itemsize * x.dtype

dtype(('<i8', (8,)))

In [12]:
type(x.itemsize)

int

In [13]:
x.size * x.itemsize

80

In [14]:
x.size

10

In [15]:
x[1:]

array([[ 6,  7,  8,  9, 10]], dtype=int64)

In [16]:
print(x[:,4])

[ 5 10]


In [17]:
x[0, 2:6]

array([3, 4, 5], dtype=int64)

In [18]:
x = np.zeros((3,3,310))

In [19]:
x

array([[[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]]])

In [23]:
x = np.ones((3,4), dtype="int32")

In [24]:
x

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [25]:
y = np.full((3,3,3), 99, dtype="int64")

In [26]:
y

array([[[99, 99, 99],
        [99, 99, 99],
        [99, 99, 99]],

       [[99, 99, 99],
        [99, 99, 99],
        [99, 99, 99]],

       [[99, 99, 99],
        [99, 99, 99],
        [99, 99, 99]]], dtype=int64)

In [30]:
z = np.full_like(y, 1)

In [31]:
z

array([[[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]], dtype=int64)

In [34]:
y.shape == z.shape

True

In [39]:
x = np.random.rand(4,2,2)

In [40]:
x

array([[[0.34265353, 0.06748474],
        [0.61517728, 0.34631003]],

       [[0.10278457, 0.19016152],
        [0.39199134, 0.63307432]],

       [[0.86022373, 0.51354868],
        [0.7894378 , 0.77814211]],

       [[0.53136683, 0.89877986],
        [0.37610385, 0.38049588]]])

#### Important

In [46]:
x = np.random.randint(5,size=(3,3))

In [47]:
x

array([[2, 3, 0],
       [2, 2, 4],
       [3, 0, 3]])

In [50]:
x = np.random.rand(3,5)

In [51]:
x

array([[9.42542044e-01, 7.22315742e-01, 3.91484335e-04, 4.59066336e-01,
        5.32845659e-01],
       [4.05312904e-01, 2.33928180e-01, 5.21676830e-01, 3.86339868e-01,
        7.15286114e-01],
       [3.20986764e-02, 2.65542709e-01, 7.19577021e-01, 3.55386204e-01,
        2.30363448e-01]])

In [55]:
i = np.identity(4, dtype="int32")

In [56]:
i

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

### Problem

In [74]:
x = np.array([[1,2,3,4]])
repeat = np.repeat(x,4, axis=0)

In [75]:
repeat

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4]])

# matrix making

In [197]:
output = np.ones((5,5))
print(output)

zeros = np.zeros((3,3))
print(zeros)

zeros[1,1] = 9
print(zeros)

output[1:4,1:4] = zeros
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [198]:
output

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [202]:
output[0:5,2]

array([1., 0., 9., 0., 1.])

In [82]:
a = np.array([1,2,3])
b = a
b[1] = 100
print(a)

[  1 100   3]


In [84]:
a = np.array([1,2,3,4,5])
b = a.copy()
b[1] = 100
print(a)

[1 2 3 4 5]


In [85]:
a

array([1, 2, 3, 4, 5])

In [86]:
a-2

array([-1,  0,  1,  2,  3])

In [87]:
a*2

array([ 2,  4,  6,  8, 10])

In [88]:
a/2

array([0.5, 1. , 1.5, 2. , 2.5])

In [89]:
 a**3

array([  1,   8,  27,  64, 125], dtype=int32)

In [98]:
abc = np.array([1,2,3,4,5], dtype="int8")

In [99]:
abc**3

array([  1,   8,  27,  64, 125], dtype=int8)

In [100]:
np.sin(abc)

array([ 0.8413,  0.909 ,  0.1411, -0.757 , -0.959 ], dtype=float16)

In [101]:
np.cos(abc)

array([ 0.5405, -0.4163, -0.99  , -0.654 ,  0.2837], dtype=float16)

In [105]:
a = np.ones((3,3), dtype = "int32")
b = np.full((3,3), 5, dtype= "int32" )
print(a)
print(b)

[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[5 5 5]
 [5 5 5]
 [5 5 5]]


In [107]:
x = a*2 + b*5

In [108]:
x

array([[27, 27, 27],
       [27, 27, 27],
       [27, 27, 27]])

In [109]:
x = np.array([[1,2,3,4],[5,6,7,8]])

In [110]:
np.min(x)

1

In [112]:
np.max(x)

8

In [113]:
np.max(x, axis=0)

array([5, 6, 7, 8])

In [114]:
np.max(x, axis=1)

array([4, 8])

### Problem

In [117]:
before = np.array([[1,2,3,4],[5,6,7,8]])

In [122]:
print(before)

[list([1, 2, 3, 4]) list([5, 6, 7, 8, 9])]


In [125]:
after = before.reshape((4,2))

ValueError: cannot reshape array of size 2 into shape (4,2)

### Data from file

In [143]:
data = np.genfromtxt('data.txt', delimiter=',', dtype="int32")

In [146]:
print(data**2)

[[  1   4   9  16  25  36  49  64  81 100]
 [121 144 169 196 225 256 289 324 361 400]
 [441 484 529 576 625 676 729 784 841 900]]


In [135]:
with open('data.txt', 'r') as file:
    data = file.read()

In [137]:
data = data.split('\n')

In [138]:
data

['1,2,3,4,5,6,7,8,9,10',
 '11,12,13,14,15,16,17,18,19,20',
 '21,23,24,25,26,27,28,29,30']

In [147]:
data = data **2

In [148]:
data

array([[  1,   4,   9,  16,  25,  36,  49,  64,  81, 100],
       [121, 144, 169, 196, 225, 256, 289, 324, 361, 400],
       [441, 484, 529, 576, 625, 676, 729, 784, 841, 900]], dtype=int32)

In [149]:
data[data > 50]

array([ 64,  81, 100, 121, 144, 169, 196, 225, 256, 289, 324, 361, 400,
       441, 484, 529, 576, 625, 676, 729, 784, 841, 900], dtype=int32)

In [189]:
output = np.ones((6,5), dtype="int32")
print(output)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [190]:
zeros = np.zeros((6,5), dtype="int32")

In [191]:
zeros

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [192]:
zeros[2,0] = 11
zeros[2,1] = 12
zeros[3,0] = 13
zeros[3,1] = 14

In [193]:
zeros

array([[ 0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0],
       [11, 12,  0,  0,  0],
       [13, 14,  0,  0,  0],
       [ 0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0]])

In [194]:
output[2:2,3:2] = zeros

ValueError: could not broadcast input array from shape (6,5) into shape (0,0)