In [1]:
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.support.ui import Select
import time
import requests as rq
import bs4
import numpy as np
import pyautogui
import time
import pickle
import pandas as pd
from sklearn.linear_model import LinearRegression
import matplotlib.pyplot as plt
from sklearn.datasets import load_boston
from sklearn.model_selection import train_test_split
import math

executable_path = "C:\\Users\\Katlic\\Downloads\\web_drivers_chrome\\chromedriver.exe"

In [96]:
df = pd.read_csv('Diabetestype.csv')
train_data = df.drop(['Type', 'Class'], axis=1)
output = df.Class
x_train, x_test, y_train, y_test = train_test_split(train_data, output, test_size=0.10, random_state = 42)
l = LinearRegression()
l.fit(x_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [97]:
train_data

Age  BS Fast  BS pp  Plasma R  Plasma F  HbA1c
0      50      6.8    8.8      11.2       7.2     62
1      31      5.2    6.8      10.9       4.2     33
2      32      6.8    8.8      11.2       7.2     62
3      21      5.7    5.8      10.7       4.8     49
4      33      6.8    8.8      11.2       7.2     62
...   ...      ...    ...       ...       ...    ...
1004   37      0.0    5.6      10.2       5.4     32
1005   23      6.3    4.2      12.2       7.8     57
1006   37     32.0    7.4       8.7       5.6     41
1007   46     19.0    6.3       7.9       3.9     40
1008   25     16.0    6.3       7.9       3.9     40

[1009 rows x 6 columns]

In [109]:
df.head()

Age  BS Fast  BS pp  Plasma R  Plasma F  HbA1c    Type  Class
0   50      6.8    8.8      11.2       7.2     62   Type1      1
1   31      5.2    6.8      10.9       4.2     33  Normal      0
2   32      6.8    8.8      11.2       7.2     62   Type1      1
3   21      5.7    5.8      10.7       4.8     49  Normal      0
4   33      6.8    8.8      11.2       7.2     62   Type1      1

In [98]:
output

0       1
1       0
2       1
3       0
4       1
       ..
1004    0
1005    1
1006    0
1007    0
1008    0
Name: Class, Length: 1009, dtype: int64

In [99]:
l.score(x_test,y_test)

0.9517311903460133

In [116]:
y_test

628    0
631    0
741    0
514    0
365    0
      ..
184    0
332    1
88     1
63     0
833    1
Name: Class, Length: 101, dtype: int64

In [102]:
x_test

Age  BS Fast  BS pp  Plasma R  Plasma F  HbA1c
628   45      0.0    7.4       8.7       5.6     41
631   24     40.0    5.8      10.7       4.8     28
741   26     20.0    7.7      11.0       6.1     36
514   24     19.0    6.3       7.9       3.9     40
365   30     28.0    5.8      10.7       4.8     28
..   ...      ...    ...       ...       ...    ...
184   40      0.0    5.6      10.2       5.4     32
332   41      6.9    8.4      11.2       7.2     62
88    43      5.6    7.2      12.2       7.8     57
63    24      4.8    7.7      11.0       6.1     36
833   59      6.8    8.2      11.6       7.4     69

[101 rows x 6 columns]

In [122]:
predict = l.predict([x_test.values[88]])

In [123]:
math.floor(predict)

1

In [124]:
y_test[88]

1

In [110]:
df

Age  BS Fast  BS pp  Plasma R  Plasma F  HbA1c    Type  Class
0      50      6.8    8.8      11.2       7.2     62   Type1      1
1      31      5.2    6.8      10.9       4.2     33  Normal      0
2      32      6.8    8.8      11.2       7.2     62   Type1      1
3      21      5.7    5.8      10.7       4.8     49  Normal      0
4      33      6.8    8.8      11.2       7.2     62   Type1      1
...   ...      ...    ...       ...       ...    ...     ...    ...
1004   37      0.0    5.6      10.2       5.4     32  Normal      0
1005   23      6.3    4.2      12.2       7.8     57   Type2      1
1006   37     32.0    7.4       8.7       5.6     41  Normal      0
1007   46     19.0    6.3       7.9       3.9     40  Normal      0
1008   25     16.0    6.3       7.9       3.9     40  Normal      0

[1009 rows x 8 columns]

In [125]:
df = pd.read_csv('cancer_reg.csv')

In [126]:
df

avganncount  avgdeathsperyear  target_deathrate  incidencerate  \
0     1397.000000               469             164.9     489.800000   
1      173.000000                70             161.3     411.600000   
2      102.000000                50             174.7     349.700000   
3      427.000000               202             194.8     430.400000   
4       57.000000                26             144.4     350.100000   
...           ...               ...               ...            ...   
3042  1962.667684                15             149.6     453.549422   
3043  1962.667684                43             150.1     453.549422   
3044  1962.667684                46             153.9     453.549422   
3045  1962.667684                52             175.0     453.549422   
3046  1962.667684                48             213.6     453.549422   

      medincome  popest2015  povertypercent  studypercap           binnedinc  \
0         61898      260131            11.2   499.748204   (61494.5, 125635]   
1         48127       43269            18.6    23.111234  (48021.6, 51046.4]   
2         49348       21026            14.6    47.560164  (48021.6, 51046.4]   
3         44243       75882            17.1   342.637253    (42724.4, 45201]   
4         49955       10321            12.5     0.000000  (48021.6, 51046.4]   
...         ...         ...             ...          ...                 ...   
3042      46961        6343            12.4     0.000000    (45201, 48021.6]   
3043      48609       37118            18.8   377.175494  (48021.6, 51046.4]   
3044      51144       34536            15.0  1968.959926  (51046.4, 54545.6]   
3045      50745       25609            13.3     0.000000  (48021.6, 51046.4]   
3046      41193       37030            13.9     0.000000  (40362.7, 42724.4]   

      medianage  ...  pctprivatecoveragealone  pctempprivcoverage  \
0          39.3  ...                      NaN                41.6   
1          33.0  ...                     53.8                43.6   
2          45.0  ...                     43.5                34.9   
3          42.8  ...                     40.3                35.0   
4          48.3  ...                     43.9                35.1   
...         ...  ...                      ...                 ...   
3042       44.2  ...                     54.9                44.6   
3043       30.4  ...                     53.3                48.6   
3044       30.9  ...                     52.6                47.8   
3045       39.0  ...                     56.3                49.6   
3046       26.2  ...                     60.3                22.9   

     pctpubliccoverage  pctpubliccoveragealone   pctwhite   pctblack  \
0                 32.9                    14.0  81.780529   2.594728   
1                 31.1                    15.3  89.228509   0.969102   
2                 42.1                    21.1  90.922190   0.739673   
3                 45.3                    25.0  91.744686   0.782626   
4                 44.0                    22.7  94.104024   0.270192   
...                ...                     ...        ...        ...   
3042              31.7                    13.2  90.280811   3.837754   
3043              28.8                    17.7  75.706245   2.326771   
3044              26.6                    16.8  87.961629   2.313188   
3045              29.5                    14.0  92.905681   1.176562   
3046              25.1                    12.6  70.098132  16.590100   

      pctasian  pctotherrace  pctmarriedhouseholds  birthrate  
0     4.821857      1.843479             52.856076   6.118831  
1     2.246233      3.741352             45.372500   4.333096  
2     0.465898      2.747358             54.444868   3.729488  
3     1.161359      1.362643             51.021514   4.603841  
4     0.665830      0.492135             54.027460   6.796657  
...        ...           ...                   ...        ...  
3042  0.327613      1.700468          

In [129]:
output = df.avgdeathsperyear

In [130]:
output

0       469
1        70
2        50
3       202
4        26
       ... 
3042     15
3043     43
3044     46
3045     52
3046     48
Name: avgdeathsperyear, Length: 3047, dtype: int64

In [140]:
train_data = df.drop(['avgdeathsperyear', 'binnedinc','pctprivatecoveragealone','geography'], axis=1)

In [143]:
train_data.head()

avganncount  target_deathrate  incidencerate  medincome  popest2015  \
0       1397.0             164.9          489.8      61898      260131   
1        173.0             161.3          411.6      48127       43269   
2        102.0             174.7          349.7      49348       21026   
3        427.0             194.8          430.4      44243       75882   
4         57.0             144.4          350.1      49955       10321   

   povertypercent  studypercap  medianage  medianagemale  medianagefemale  \
0            11.2   499.748204       39.3           36.9             41.7   
1            18.6    23.111234       33.0           32.2             33.7   
2            14.6    47.560164       45.0           44.0             45.8   
3            17.1   342.637253       42.8           42.2             43.4   
4            12.5     0.000000       48.3           47.8             48.9   

   ...  pctprivatecoverage  pctempprivcoverage  pctpubliccoverage  \
0  ...                75.1                41.6               32.9   
1  ...                70.2                43.6               31.1   
2  ...                63.7                34.9               42.1   
3  ...                58.4                35.0               45.3   
4  ...                61.6                35.1               44.0   

   pctpubliccoveragealone   pctwhite  pctblack  pctasian  pctotherrace  \
0                    14.0  81.780529  2.594728  4.821857      1.843479   
1                    15.3  89.228509  0.969102  2.246233      3.741352   
2                    21.1  90.922190  0.739673  0.465898      2.747358   
3                    25.0  91.744686  0.782626  1.161359      1.362643   
4                    22.7  94.104024  0.270192  0.665830      0.492135   

   pctmarriedhouseholds  birthrate  
0             52.856076   6.118831  
1             45.372500   4.333096  
2             54.444868   3.729488  
3             51.021514   4.603841  
4             54.027460   6.796657  

[5 rows x 29 columns]

In [144]:
x_train, x_test, y_train, y_test = train_test_split(train_data, output, test_size=0.10, random_state = 42)
l = LinearRegression()
l.fit(x_train, y_train)

ValueError: Input contains NaN, infinity or a value too large for dtype('float64').

In [15]:
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split

In [3]:
data = load_breast_cancer()

In [4]:
data.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,

In [10]:
x = data.data

In [11]:
x

array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
        1.189e-01],
       [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
        8.902e-02],
       [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
        8.758e-02],
       ...,
       [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
        7.820e-02],
       [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
        1.240e-01],
       [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
        7.039e-02]])

In [24]:
df = pd.DataFrame(data.data, columns = data.feature_names)
x_train, x_test, y_train, y_test = train_test_split(df, data.target, test_size=0.10, random_state = 12)
lr = LinearRegression()
lr.fit(x_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [25]:
lr.score(x_test,y_test)

0.7354602549334172

In [27]:
lr.predict([x_test.values[0]])

array([0.39233405])

In [28]:
y_test[0]

0