In [1]:
print("Numpy")

Numpy


In [2]:
import numpy as np

In [3]:
array = np.array([[1,2,3], [4,5,6]])

In [6]:
for items in array:
    for item in items:
        print(item,end= " ")
    print()

1 2 3 
4 5 6 


In [7]:
array = np.array([(1,2,3), (4,5,6)])

In [8]:
print(array)

[[1 2 3]
 [4 5 6]]


In [9]:
print(type(array))

<class 'numpy.ndarray'>


In [14]:
x = np.zeros((3,3))

In [16]:
x[0][0]

0.0

In [17]:
x

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [18]:
np.ones((3,7))

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [19]:
np.random.randn(5)

array([-0.76632988,  0.9260409 , -0.49890052,  1.75924642,  1.16525841])

In [21]:
np.random.randint(25,35)

29

In [22]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [23]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

####  Equidistance values

In [28]:
np.linspace(0,10,11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [29]:
np.linspace(1,10,11)

array([ 1. ,  1.9,  2.8,  3.7,  4.6,  5.5,  6.4,  7.3,  8.2,  9.1, 10. ])

In [30]:
np.linspace(2,10,11)

array([ 2. ,  2.8,  3.6,  4.4,  5.2,  6. ,  6.8,  7.6,  8.4,  9.2, 10. ])

In [32]:
np.logspace(0,10,10)

array([1.00000000e+00, 1.29154967e+01, 1.66810054e+02, 2.15443469e+03,
       2.78255940e+04, 3.59381366e+05, 4.64158883e+06, 5.99484250e+07,
       7.74263683e+08, 1.00000000e+10])

In [33]:
array = np.array([(1,2,3), (4,5,6)])

In [34]:
array

array([[1, 2, 3],
       [4, 5, 6]])

In [35]:
new_array = np.array(['a','b','c'], dtype=np.object)

In [36]:
new_array

array(['a', 'b', 'c'], dtype=object)

In [38]:
new_array.shape

(3,)

In [41]:
n = np.random.randn(25)

In [42]:
n.reshape(5,5)

array([[-0.42470243, -1.12246065, -2.13615167,  0.75295733,  0.19616089],
       [-1.33013697, -0.15109984,  0.32318086,  1.04957384, -2.24933083],
       [ 1.35590146,  0.40379896, -0.52217391,  0.09231301,  1.5440906 ],
       [-1.21437644, -0.17915583,  0.79276321,  0.76086768,  0.38400769],
       [-0.39659709,  2.1013601 ,  0.01455223,  1.77007203, -1.64896363]])

In [43]:
n.reshape(25,1)

array([[-0.42470243],
       [-1.12246065],
       [-2.13615167],
       [ 0.75295733],
       [ 0.19616089],
       [-1.33013697],
       [-0.15109984],
       [ 0.32318086],
       [ 1.04957384],
       [-2.24933083],
       [ 1.35590146],
       [ 0.40379896],
       [-0.52217391],
       [ 0.09231301],
       [ 1.5440906 ],
       [-1.21437644],
       [-0.17915583],
       [ 0.79276321],
       [ 0.76086768],
       [ 0.38400769],
       [-0.39659709],
       [ 2.1013601 ],
       [ 0.01455223],
       [ 1.77007203],
       [-1.64896363]])

In [44]:
n.reshape(-1,1)

array([[-0.42470243],
       [-1.12246065],
       [-2.13615167],
       [ 0.75295733],
       [ 0.19616089],
       [-1.33013697],
       [-0.15109984],
       [ 0.32318086],
       [ 1.04957384],
       [-2.24933083],
       [ 1.35590146],
       [ 0.40379896],
       [-0.52217391],
       [ 0.09231301],
       [ 1.5440906 ],
       [-1.21437644],
       [-0.17915583],
       [ 0.79276321],
       [ 0.76086768],
       [ 0.38400769],
       [-0.39659709],
       [ 2.1013601 ],
       [ 0.01455223],
       [ 1.77007203],
       [-1.64896363]])

In [47]:
n.reshape(1,25)

array([[-0.42470243, -1.12246065, -2.13615167,  0.75295733,  0.19616089,
        -1.33013697, -0.15109984,  0.32318086,  1.04957384, -2.24933083,
         1.35590146,  0.40379896, -0.52217391,  0.09231301,  1.5440906 ,
        -1.21437644, -0.17915583,  0.79276321,  0.76086768,  0.38400769,
        -0.39659709,  2.1013601 ,  0.01455223,  1.77007203, -1.64896363]])

In [48]:
# resize  ===> actually change the array 
# reshape ===> returns a copy of reshape array

In [50]:
# one d array
n.ravel()

array([-0.42470243, -1.12246065, -2.13615167,  0.75295733,  0.19616089,
       -1.33013697, -0.15109984,  0.32318086,  1.04957384, -2.24933083,
        1.35590146,  0.40379896, -0.52217391,  0.09231301,  1.5440906 ,
       -1.21437644, -0.17915583,  0.79276321,  0.76086768,  0.38400769,
       -0.39659709,  2.1013601 ,  0.01455223,  1.77007203, -1.64896363])

In [56]:
a = np.ones((3,3))

In [57]:
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [76]:
a[0][0] = 5

In [77]:
a[1][0] = 6

In [78]:
a[2][0] = 7

In [84]:
a

array([[5., 1., 1.],
       [6., 1., 1.],
       [7., 1., 1.]])

In [85]:
w = a.T

In [86]:
w

array([[5., 6., 7.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [87]:
np.matmul(x,w)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [88]:
a

array([[5., 1., 1.],
       [6., 1., 1.],
       [7., 1., 1.]])

In [89]:
np.matmul(a,a)

array([[38.,  7.,  7.],
       [43.,  8.,  8.],
       [48.,  9.,  9.]])